package:
  name: llvmdev
  version: "3.5.1p1"

source:
  fn: 3.5.1.tar.gz
  url: https://github.com/numba/llvm-mirror/archive/3.5.1p1.tar.gz

build:
  number: 0

requirements:
  build:
    - system           [linux and not armv6]
  run:
    - system           [linux and not armv6]

#test:
  #commands:
    #- clang --help     [linux and not armv6]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.5.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
